// Adult XML whitelist ported from local KskXmlBuilder; no runtime eval.
// Source SHA256: 80962fa64fd9e37b77054003ece37f1cc482172ef66b6fb3ba800fc7641e9111
export function adultBlocks(dto, benhVien, entity, h) {
const {giaTriXmlKskNguoiLon,dinhDangNgaySinhXmlKsk,dinhDangNgayXmlKsk,dinhDangNgayGioXmlKsk,
firstNonBlank,maNgheNghiepCap2DayCongVneid,bloodName,maCskcbXmlKsk,maGlnXmlKsk,
giaTriXmlDsDoiTuongKsk,maLoaiKcbKskDinhKy,thoiGianVaoXmlKsk,
giaTriHuyetApXmlKsk,chuKyDienTuBacSi,giaTriThiLucDayByt,isBlank}=h;
const TYPE_KSK_NGUOI_LON="Adult";
const tienSu=dto.tienSu,tuVan=dto.tuVan,khamLamSang=dto.khamLamSang;
const blocks={};
blocks["XML1"]={tag:"THONG_TIN_HANH_CHINH",data:{}};
blocks["XML1"].data["HO_TEN"]=giaTriXmlKskNguoiLon(dto?.tenNb);
blocks["XML1"].data["GIOI_TINH"]=giaTriXmlKskNguoiLon(dto?.gioiTinh);
blocks["XML1"].data["NGAY_SINH"]=giaTriXmlKskNguoiLon(dinhDangNgaySinhXmlKsk(dto?.ngaySinh, dto?.chiNamSinh));
blocks["XML1"].data["MA_DAN_TOC"]=giaTriXmlKskNguoiLon(dto?.maDanToc);
blocks["XML1"].data["SO_CCCD"]=giaTriXmlKskNguoiLon(dto?.maSoGiayToTuyThan);
blocks["XML1"].data["NGAYCAP_CCCD"]=giaTriXmlKskNguoiLon(dinhDangNgayXmlKsk(dto?.ngayCap));
blocks["XML1"].data["NOICAP_CCCD"]=giaTriXmlKskNguoiLon(dto?.noiCap);
blocks["XML1"].data["DIA_CHI"]=giaTriXmlKskNguoiLon(dto?.diaChi);
blocks["XML1"].data["MATINH_CU_TRU"]=giaTriXmlKskNguoiLon(firstNonBlank(dto?.maTuongDuongTinhThanhPho, dto?.maTinhThanhPho));
blocks["XML1"].data["MAXA_CU_TRU"]=giaTriXmlKskNguoiLon(firstNonBlank(dto?.maTuongDuongXaPhuong, dto?.maXaPhuong));
blocks["XML1"].data["DIEN_THOAI"]=giaTriXmlKskNguoiLon(dto?.soDienThoai);
blocks["XML1"].data["MA_NGHE_NGHIEP"]=giaTriXmlKskNguoiLon(maNgheNghiepCap2DayCongVneid(dto?.maNgheNghiep));
blocks["XML1"].data["NOI_LAM_VIEC_HOC_TAP"]=giaTriXmlKskNguoiLon(dto?.noiCongTacHienTai);
blocks["XML1"].data["LY_DO_VV"]=giaTriXmlKskNguoiLon(dto?.lyDoDenKham);
blocks["XML1"].data["NHOM_MAU"]=giaTriXmlKskNguoiLon(dto?.nhomMau == null ? null : bloodName(dto.nhomMau));
blocks["XML2"]={tag:"THONG_TIN_CHUNG_VE_LAN_KHAM",data:{}};
blocks["XML2"].data["MA_LK"]=giaTriXmlKskNguoiLon(dto?.maHoSo);
blocks["XML2"].data["TYPE"]=TYPE_KSK_NGUOI_LON;
blocks["XML2"].data["MA_CSKCB"]=maCskcbXmlKsk(benhVien);
blocks["XML2"].data["MA_GTIN_CSKCB"]=maGlnXmlKsk(dto, benhVien);
blocks["XML2"].data["DOI_TUONG"]=giaTriXmlDsDoiTuongKsk(dto?.dsDoiTuongKsk);
blocks["XML2"].data["NGUON_CHI_TRA"]=giaTriXmlKskNguoiLon(dto?.nguonKinhPhiKham);
blocks["XML2"].data["MA_LOAI_KCB"]=maLoaiKcbKskDinhKy(null);
blocks["XML2"].data["NGAY_VAO"]=giaTriXmlKskNguoiLon(dinhDangNgayGioXmlKsk(thoiGianVaoXmlKsk(dto)));
blocks["XML7"]={tag:"KHAM_LAM_SANG",data:{}};
blocks["XML7"].data["NOI_KHOA_TUAN_HOAN"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.noiKhoaTuanHoan);
blocks["XML7"].data["NOI_KHOA_TUAN_HOAN_PL"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.noiKhoaTuanHoanPl);
blocks["XML7"].data["CKDT_NOI_KHOA_TUAN_HOAN"]=chuKyDienTuBacSi(entity == null ? null : entity?.bacSiKhamTuanHoanHoHapId);
blocks["XML7"].data["NOI_KHOA_HO_HAP"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.noiKhoaHoHap);
blocks["XML7"].data["NOI_KHOA_HO_HAP_PL"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.noiKhoaHoHapPl);
blocks["XML7"].data["CKDT_NOI_KHOA_HO_HAP"]=chuKyDienTuBacSi(entity == null ? null : entity?.bacSiKhamTuanHoanHoHapId);
blocks["XML7"].data["NOI_KHOA_TIEU_HOA"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.noiKhoaTieuHoa);
blocks["XML7"].data["NOI_KHOA_TIEU_HOA_PL"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.noiKhoaTieuHoaPl);
blocks["XML7"].data["CKDT_NOI_KHOA_TIEU_HOA"]=chuKyDienTuBacSi(entity == null ? null : entity?.bacSiKhamTieuHoaId);
blocks["XML7"].data["NOI_KHOA_THAN_TN_SD"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.noiKhoaThanTietNieu);
blocks["XML7"].data["NOI_KHOA_THAN_TN_SD_PL"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.noiKhoaThanTietNieuPl);
blocks["XML7"].data["CKDT_NOI_KHOA_THAN_TN_SD"]=chuKyDienTuBacSi(entity == null ? null : entity?.bacSiKhamThanTietLieuId);
blocks["XML7"].data["NOI_KHOA_NOI_TIET"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.noiKhoaNoiTiet);
blocks["XML7"].data["NOI_KHOA_NOI_TIET_PL"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.noiKhoaNoiTietPl);
blocks["XML7"].data["CKDT_NOI_KHOA_NOI_TIET"]=chuKyDienTuBacSi(entity == null ? null : entity?.bacSiKhamNoiTietId);
blocks["XML7"].data["NOI_KHOA_CO_XUONG_KHOP"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.noiKhoaCoXuongKhop);
blocks["XML7"].data["NOI_KHOA_CO_XUONG_KHOP_PL"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.noiKhoaCoXuongKhopPl);
blocks["XML7"].data["CKDT_NOI_KHOA_CO_XUONG_KHOP"]=chuKyDienTuBacSi(entity == null ? null : entity?.bacSiKhamCoXuongKhopId);
blocks["XML7"].data["NOI_KHOA_THAN_KINH"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.noiKhoaThanKinh);
blocks["XML7"].data["NOI_KHOA_THAN_KINH_PL"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.noiKhoaThanKinhPl);
blocks["XML7"].data["CKDT_NOI_KHOA_THAN_KINH"]=chuKyDienTuBacSi(entity == null ? null : entity?.bacSiKhamThanKinhTamThanId);
blocks["XML7"].data["NOI_KHOA_TAM_THAN"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.noiKhoaTamThan);
blocks["XML7"].data["NOI_KHOA_TAM_THAN_PL"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.noiKhoaTamThanPl);
blocks["XML7"].data["CKDT_NOI_KHOA_TAM_THAN"]=chuKyDienTuBacSi(entity == null ? null : entity?.bacSiKhamThanKinhTamThanId);
blocks["XML7"].data["KET_QUA_KHAM_NGOAI_KHOA"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.ketQuaKhamNgoaiKhoa);
blocks["XML7"].data["KHAM_NGOAI_KHOA_PL"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.khamNgoaiKhoaPl);
blocks["XML7"].data["CKDT_KHAM_NGOAI_KHOA"]=chuKyDienTuBacSi(entity == null ? null : entity?.bacSiKhamNgoaiId);
blocks["XML7"].data["KET_QUA_KHAM_DA_LIEU"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.ketQuaKhamDaLieu);
blocks["XML7"].data["KHAM_DA_LIEU_PL"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.khamDaLieuPl);
blocks["XML7"].data["CKDT_KHAM_DA_LIEU"]=chuKyDienTuBacSi(entity == null ? null : entity?.bacSiKhamDaLieuId);
blocks["XML7"].data["KET_QUA_KHAM_SAN_PHU_KHOA"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.ketQuaKhamSanPhuKhoa);
blocks["XML7"].data["KHAM_SAN_PHU_KHOA_PL"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.khamSanPhuKhoaPl);
blocks["XML7"].data["CKDT_KHAM_SAN_PHU_KHOA"]=chuKyDienTuBacSi(entity == null ? null : entity?.bacSiKhamSanId);
blocks["XML7"].data["KHONG_KINH_MAT_PHAI"]=giaTriXmlKskNguoiLon(giaTriThiLucDayByt( khamLamSang == null ? null : khamLamSang?.khongKinhMatPhai));
blocks["XML7"].data["KHONG_KINH_MAT_TRAI"]=giaTriXmlKskNguoiLon(giaTriThiLucDayByt( khamLamSang == null ? null : khamLamSang?.khongKinhMatTrai));
blocks["XML7"].data["CO_KINH_MAT_PHAI"]=giaTriXmlKskNguoiLon(giaTriThiLucDayByt( khamLamSang == null ? null : khamLamSang?.coKinhMatPhai));
blocks["XML7"].data["CO_KINH_MAT_TRAI"]=giaTriXmlKskNguoiLon(giaTriThiLucDayByt( khamLamSang == null ? null : khamLamSang?.coKinhMatTrai));
blocks["XML7"].data["BENH_KHAC_MAT"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.benhKhacMat);
blocks["XML7"].data["KHAM_MAT_PL"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.khamMatPl);
blocks["XML7"].data["CKDT_KHAM_MAT"]=chuKyDienTuBacSi(entity == null ? null : entity?.bacSiKhamMatId);
blocks["XML7"].data["TAI_TRAI_NOI_THUONG"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.taiTraiNoiThuong);
blocks["XML7"].data["TAI_TRAI_NOI_THAM"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.taiTraiNoiTham);
blocks["XML7"].data["TAI_PHAI_NOI_THUONG"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.taiPhaiNoiThuong);
blocks["XML7"].data["TAI_PHAI_NOI_THAM"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.taiPhaiNoiTham);
blocks["XML7"].data["BENH_KHAC_TAI_MUI_HONG"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.benhKhacTaiMuiHong);
blocks["XML7"].data["KHAM_TAI_MUI_HONG_PL"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.khamTaiMuiHongPl);
blocks["XML7"].data["CKDT_KHAM_TAI_MUI_HONG"]=chuKyDienTuBacSi(entity == null ? null : entity?.bacSiKhamTmhId);
blocks["XML7"].data["HAM_TREN"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.hamTren);
blocks["XML7"].data["HAM_DUOI"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.hamDuoi);
blocks["XML7"].data["BENH_KHAC_RANG_HAM_MAT"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.benhKhacRangHamMat);
blocks["XML7"].data["KHAM_RANG_HAM_MAT_PL"]=giaTriXmlKskNguoiLon(khamLamSang == null ? null : khamLamSang?.khamRangHamMatPl);
blocks["XML7"].data["CKDT_KHAM_RANG_HAM_MAT"]=chuKyDienTuBacSi(entity == null ? null : entity?.bacSiKhamRhmId);
blocks["XML8"]={tag:"KET_LUAN_VA_TU_VAN",data:{}};
blocks["XML8"].data["BINH_THUONG"]=giaTriXmlKskNguoiLon(tuVan == null ? null : tuVan?.binhThuong);
blocks["XML8"].data["NGUY_CO_MAC_LAO"]=giaTriXmlKskNguoiLon(tuVan == null ? null : tuVan?.nguyCoMacLao);
blocks["XML8"].data["VAN_DE_SUC_KHOE"]=giaTriXmlKskNguoiLon(tuVan == null ? null : tuVan?.vanDeSucKhoe);
blocks["XML8"].data["KET_LUAN_BENH"]=giaTriXmlKskNguoiLon(tuVan == null ? null : tuVan?.ketLuanBenh);
blocks["XML8"].data["GHI_RO_VAN_DE_SUC_KHOE"]=giaTriXmlKskNguoiLon(tuVan == null ? null : tuVan?.ghiRoVanDeSucKhoe);
blocks["XML8"].data["HEN_KHAM_LAN_SAU"]=giaTriXmlKskNguoiLon(tuVan == null ? null : tuVan?.tuVanHenKhamLanSau);
blocks["XML8"].data["CHUYEN_CSKCB"]="";
blocks["XML9"]={tag:"TIEN_SU_BENH_TAT",data:{}};
blocks["XML9"].data["TSGD_MAC_BENH"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tsgdMacBenh);
blocks["XML9"].data["TSGD_MA_BENH"]=giaTriXmlKskNguoiLon(dto?.tienSuGiaDinh);
blocks["XML9"].data["TIEM_CHUNG_BCG"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tiemChungBcg);
blocks["XML9"].data["TIEM_CHUNG_BH_HG_UV"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tiemChungBhHgUv);
blocks["XML9"].data["TIEM_CHUNG_SOI"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tiemChungSoi);
blocks["XML9"].data["TIEM_CHUNG_BAI_LIET"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tiemChungBaiLiet);
blocks["XML9"].data["TIEM_CHUNG_VNNB_B"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tiemChungVnnbB);
blocks["XML9"].data["TIEM_CHUNG_VGB"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tiemChungVgb);
blocks["XML9"].data["TIEM_CHUNG_CAC_LOAI_KHAC"]="";
blocks["XML9"].data["TSBT_MAC_BENH"]=giaTriXmlKskNguoiLon( isBlank(firstNonBlank(tienSu == null ? null : tienSu?.tsbtMaBenh, dto?.tienSuBanThan)) ? 0 : 1);
blocks["XML9"].data["TSBT_MA_BENH"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tsbtMaBenh);
blocks["XML9"].data["TSBT_DANG_DIEU_TRI_BENH"]=giaTriXmlKskNguoiLon( tienSu == null ? null : tienSu?.tsbtDangDieuTriBenh != null ? tienSu?.tsbtDangDieuTriBenh : tienSu?.coDangDieuTriBenh);
blocks["XML9"].data["BENH_DANG_DIEU_TRI"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tenBenhDangDieuTri);
blocks["XML9"].data["TSBT_BENH_TRONG_5_NAM_QUA"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tsbtBenhTrong5NamQua);
blocks["XML9"].data["TSBT_BENH_THAN_KINH"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tsbtBenhThanKinh);
blocks["XML9"].data["TSBT_BENH_MAT"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tsbtBenhMat);
blocks["XML9"].data["TSBT_BENH_TAI"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tsbtBenhTai);
blocks["XML9"].data["TSBT_BENH_TIM"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tsbtBenhTim);
blocks["XML9"].data["TSBT_PHAU_THUAT_TIM"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tsbtPhauThuatTim);
blocks["XML9"].data["TSBT_TANG_HUYET_AP"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tsbtTangHuyetAp);
blocks["XML9"].data["TSBT_KHO_THO"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tsbtKhoTho);
blocks["XML9"].data["TSBT_BENH_PHOI"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tsbtBenhPhoi);
blocks["XML9"].data["TSBT_BENH_THAN"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tsbtBenhThan);
blocks["XML9"].data["TSBT_NGHIEN_RUOU"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tsbtNghienRuou);
blocks["XML9"].data["TSBT_DAI_THAO_DUONG"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tsbtDaiThaoDuong);
blocks["XML9"].data["TSBT_BENH_TAM_THAN"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tsbtBenhTamThan);
blocks["XML9"].data["TSBT_MAT_Y_THUC"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tsbtMatYThuc);
blocks["XML9"].data["TSBT_NGAT"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tsbtNgat);
blocks["XML9"].data["TSBT_BENH_TIEU_HOA"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tsbtBenhTieuHoa);
blocks["XML9"].data["TSBT_ROI_LOAN_GIAC_NGU"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tsbtRoiLoanGiacNgu);
blocks["XML9"].data["TSBT_TAI_BIEN"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tsbtTaiBien);
blocks["XML9"].data["TSBT_BENH_COT_SONG"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tsbtBenhCotSong);
blocks["XML9"].data["TSBT_RUOU_THUONG_XUYEN"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tsbtRuouThuongXuyen);
blocks["XML9"].data["TSBT_MA_TUY"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tsbtMaTuy);
blocks["XML9"].data["TSBT_BENH_KHAC"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tsbtBenhKhac);
blocks["XML9"].data["TSBT_MA_BENH_KHAC"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tsbtMaBenhKhac);
blocks["XML9"].data["TSBT_TEN_THUOC_LIEU_LUONG"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tsbtTenThuocLieuLuong);
blocks["XML9"].data["TSBT_THAI_SAN"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tsbtThaiSan);
blocks["XML9"].data["TSBT_MA_BENH_THAI_SAN"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tsbtMaBenhThaiSan);
blocks["XML9"].data["TSBT_TEN_THUOC_THAI_SAN"]=giaTriXmlKskNguoiLon(tienSu == null ? null : tienSu?.tsbtTenThuocThaiSan);
blocks["XML10"]={tag:"KHAM_THE_LUC",data:{}};
blocks["XML10"].data["CHIEU_CAO"]=giaTriXmlKskNguoiLon(dto?.chieuCao);
blocks["XML10"].data["CAN_NANG"]=giaTriXmlKskNguoiLon(dto?.canNang);
blocks["XML10"].data["CHI_SO_BMI"]=giaTriXmlKskNguoiLon(dto?.bmi);
blocks["XML10"].data["MACH"]=giaTriXmlKskNguoiLon(dto?.mach);
blocks["XML10"].data["HUYET_AP"]=giaTriXmlKskNguoiLon(giaTriHuyetApXmlKsk(dto?.huyetApTamThu, dto?.huyetApTamTruong));
blocks["XML10"].data["KHAM_THE_LUC_PL"]=giaTriXmlKskNguoiLon(dto?.khamTheLucPl);
blocks["XML12"]={tag:"KET_LUAN",data:{}};
blocks["XML12"].data["PHAN_LOAI_SK"]=giaTriXmlKskNguoiLon(tuVan == null ? null : tuVan?.phanLoaiSk);
blocks["XML12"].data["KET_LUAN_BENH"]=giaTriXmlKskNguoiLon(tuVan == null ? null : tuVan?.ketLuanBenh);
blocks["XML12"].data["CAC_VAN_DE_SUC_KHOE"]=giaTriXmlKskNguoiLon(tuVan == null ? null : tuVan?.ghiRoVanDeSucKhoe);
blocks["XML12"].data["CAC_BENH_TAT_NEU_CO"]=giaTriXmlKskNguoiLon(tuVan == null ? null : tuVan?.cacBenhTatNeuCo);
return blocks;
}
