import {catalogServiceCodes,validId,clsQuery,childCatalogQuery,hospitalQuery,normalizeCls,mapLisCls,selectCls,buildAdult,xmlString,gatewayBase,gatewayLoginToken,envelope,blank} from './core.js';
const $=id=>document.getElementById(id);
let source=null,prepared=null,preparedSnapshot='',importedSigned=null,busy=false,localCsrf=null;
const status=(id,text,error=false)=>{$(id).textContent=text;$(id).className='app-feedback'+(error?' error':'');};
const snapshot=()=>JSON.stringify(['xml','gatewayUrl','sender','receiver','version','privateKey','transport','recordId','gatewayUser','gatewayPassword','gatewayToken'].map(k=>$(k).value));
function invalidate(){prepared=null;preparedSnapshot='';$('push').disabled=true;$('payload').textContent='';$('target').textContent='';}
async function safe(fn,id='status'){if(busy)return;busy=true;$('load').disabled=true;$('prepare').disabled=true;$('push').disabled=true;try{await fn();}catch(e){status(id,e.message,true);}finally{busy=false;$('load').disabled=false;$('prepare').disabled=false;$('push').disabled=!prepared||snapshot()!==preparedSnapshot;}}
function clean(html){const doc=new DOMParser().parseFromString(String(html??''),'text/html');doc.querySelectorAll('script,style').forEach(e=>e.remove());doc.querySelectorAll('br').forEach(e=>e.replaceWith(' '));return (doc.body.textContent||'').replace(/\s+/g,' ').trim();}
function parseXml(xml){if(/<!DOCTYPE|<!ENTITY/i.test(xml))throw Error('XML không được có DOCTYPE/ENTITY.');const doc=new DOMParser().parseFromString(xml,'application/xml');if(doc.getElementsByTagName('parsererror').length)throw Error('XML sai cú pháp: '+doc.getElementsByTagName('parsererror')[0].textContent.slice(0,250));if(doc.documentElement.nodeName!=='KHAMSUCKHOE')throw Error('Root XML phải là KHAMSUCKHOE.');return doc;}
const hasSigned=doc=>!!doc.getElementsByTagNameNS('http://www.w3.org/2000/09/xmldsig#','Signature').length||['CKS_NGUOI_KET_LUAN','CKS_BENH_VIEN'].some(tag=>[...doc.getElementsByTagName(tag)].some(n=>n.children.length||n.textContent.trim()));
function checkXml(){const doc=parseXml($('xml').value);const rows=[...doc.getElementsByTagName('CHI_TIET_CLS')];const get=(n,t)=>(n.getElementsByTagName(t)[0]?.textContent||'').trim();const missing=rows.filter(n=>!get(n,'MA_CHI_SO')).length;const units=rows.filter(n=>get(n,'DON_VI_DO').toLocaleLowerCase('vi')==='lần').length;
 if(hasSigned(doc)&&$('xml').value!==importedSigned)throw Error('XML có chữ ký nhưng nội dung đã sửa hoặc chưa được nhập từ file gốc. Nhập lại XML đã ký, hoặc tạo bản nháp bỏ chữ ký và ký lại bên ngoài.');
 const gln=doc.getElementsByTagName('THONGTINDONVI')[0]?.getElementsByTagName('MACSKCB')[0]?.textContent.trim();if(!gln)throw Error('XML thiếu MACSKCB (GLN) trong THONGTINDONVI.');
 const warnings=[`${rows.length} dòng CLS; ${missing} dòng trống mã chỉ số; ${units} dòng dùng đơn vị “Lần”.`,hasSigned(doc)?'XML có chữ ký tài liệu; tool không xác minh chứng thư.':'XML nháp chưa ký tài liệu. Cổng có thể yêu cầu chữ ký hợp lệ.'];
 status('validation',warnings.join('\n'));return {doc,gln};}
async function bridge(url,options={}){if(!['127.0.0.1','localhost'].includes(location.hostname))throw Error('Helper chỉ dùng khi mở tool tại http://127.0.0.1:8766.');if(!localCsrf){const r=await fetch('/__ksk/session',{redirect:'error'});if(!r.ok)throw Error('Chưa chạy helper KSK.');localCsrf=(await r.json()).csrf;}
 const response=await fetch('/__ksk/proxy',{method:'POST',headers:{'Content-Type':'application/json','X-KSK-CSRF':localCsrf},body:JSON.stringify({url,method:options.method||'GET',headers:Object.fromEntries(new Headers(options.headers||{})),body:options.body??null}),signal:AbortSignal.timeout(65000),redirect:'error'});return response;}
async function hisRequest(path,options={}){if($('transport').value!=='local')return IsofhApp.request(path,options);const session=IsofhApp.requireSession();const headers=new Headers(options.headers||{});headers.set('Authorization','Bearer '+session.token);headers.set('Accept-Language','vi');const originSession=session.base+'|'+session.account+'|'+session.token;const r=await bridge(session.base+path,{...options,headers});const now=IsofhApp.session();if(!now||originSession!==now.base+'|'+now.account+'|'+now.token)throw Error('Phiên HIS đã thay đổi. Lấy lại dữ liệu.');return r;}
async function hisJson(path){const r=await hisRequest(path),j=await r.json();if(!r.ok||(j.code!==undefined&&j.code!==0))throw Error(j.message||`HIS HTTP ${r.status}`);return j.data;}
async function query(sql){const r=await hisRequest('/dm-mau-du-lieu/db/query',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify([sql])});const type=r.headers.get('Content-Type')||'';if(!r.ok)throw Error('Query HIS thất bại (HTTP '+r.status+').');if(type.includes('json')){const j=await r.json();if(j.code!==undefined&&j.code!==0)throw Error(j.message||'Query HIS lỗi.');const data=j.data??j;if(Array.isArray(data))return data;throw Error('Query không trả danh sách dữ liệu.');}const sheets=await IsofhXlsx.readWorkbook(await r.arrayBuffer());return sheets.flatMap(s=>s.rows);}
function renderSource(){if(!source)return;invalidate();const dto=source.dto;const live=normalizeCls(source.clsRows||[],clean),mode=$('clsSource').value;
 if(mode==='mapped'&&!Array.isArray(source.childCatalogRows)){$('xml').value='';$('sourceData').textContent=JSON.stringify(source,null,2);$('clsTable').replaceChildren();$('summary').textContent='Nguồn JSON cũ chưa có danh mục chỉ số con. Query lại phiếu, hoặc chọn nguồn CLS theo HIS.';throw Error('Query lại phiếu để lấy mã gửi LIS, mã tương đương và đơn vị danh mục mới.');}
 const selected=mode==='mapped'?mapLisCls(live,source.childCatalogRows):selectCls(dto,live,mode);
 $('xml').value=xmlString(buildAdult(dto,source.benhVien,source.entity,selected,source.signatures||{}));importedSigned=null;$('sender').value=dto.maGln||source.benhVien.maGln||'';
 const mapped=selected.filter(c=>c.mapping?.status==='mapped').length,unresolved=selected.filter(c=>c.mapping&&!['mapped','not-child'].includes(c.mapping.status)).length;
 const mappingSummary=mode==='mapped'?`\nÁnh xạ được ${mapped} chỉ số; ${unresolved} chỉ số cần kiểm tra. Lấy đơn vị đúng như DM, kể cả để trống. Giá trị kết quả giữ nguyên, chưa quy đổi theo đơn vị mới.`:'';
 $('summary').textContent=`Phiếu ${source.id} · ${dto.tenNb||''} · ${dto.maHoSo||''}\nQuery mới: ${live.length} dòng; XML nháp: ${selected.length} dòng (${mode==='mapped'?'CLS query + ánh xạ danh mục LIS':mode==='saved'&&dto.khamCanLamSang?.dsCls?.length?'CLS đã lưu trên phiếu':'CLS từ query hiện tại'}).${mappingSummary}\nKhông tự dùng lại XML đã ký trong lịch sử HIS; dùng Mở XML nếu cần đúng bản đã ký. Các ảnh CKDT bác sĩ chưa đọc được sẽ để trống.`;
 $('sourceData').textContent=JSON.stringify({...source,clsMode:mode,selectedCls:selected},null,2);$('clsTable').replaceChildren();for(const c of selected){const tr=document.createElement('tr');const codes=catalogServiceCodes(c,source.clsRows||[]);
 const originalUnit=c.mapping?.originalUnit??c.donViDo;
 const values=[c.maDichVu,codes.length?codes.join(' / ')+(codes.length>1?' (trùng mã đẩy)':''):'—',c.maLis??'—',c.mapping?.originalCode??c.maChiSo,c.maChiSo,c.tenChiSo,c.giaTri,[originalUnit,blank(c.donViLis)?'':`(LIS: ${c.donViLis})`].filter(v=>!blank(v)).join(' '),c.donViDo,c.mapping?.label??'Giữ theo nguồn đã chọn'];
 for(const v of values){const td=document.createElement('td');td.textContent=v??'';tr.append(td);}if(c.mapping&&!['mapped','not-child'].includes(c.mapping.status))tr.className='mapping-warning';$('clsTable').append(tr);}checkXml();}
async function load(){const id=validId($('recordId').value);source=null;invalidate();$('xml').value='';$('sourceData').textContent='';$('clsTable').replaceChildren();status('status','Đang đọc phiếu và query CLS…');const session=IsofhApp.requireSession(),identity=session.base+'|'+session.account;
 const entity=await hisJson('/nb-kham-ksk/'+id);if(!entity||Number(entity.loai)!==30)throw Error('Phiếu không tồn tại hoặc không phải mẫu đủ 18 tuổi. Có thể mở XML sẵn để kiểm thử cổng.');
 const sql=clsQuery(id),csql=childCatalogQuery(id);$('sql').textContent=sql+'\n\n'+csql;const [dto,clsRows,childCatalogRows]=await Promise.all([hisJson('/nb-kham-ksk/phieu-ksk-dinh-ky/'+id),query(sql),query(csql)]);
 if(!dto||String(dto.nbDotDieuTriId??dto.id)!==id)throw Error('ID phiếu trả về không khớp.');
 const branch=dto.coSoKcbId??entity.coSoKcbId;if(!branch)throw Error('Phiếu thiếu cơ sở KCB; cần kiểm tra trước khi xác định bệnh viện.');
 const hsql=hospitalQuery(branch),hospitals=await query(hsql);$('sql').textContent+='\n\n'+hsql;if(hospitals.length!==1)throw Error('Không xác định duy nhất bệnh viện từ MA_BENH_VIEN. Kiểm tra thiết lập tại cơ sở KCB.');const bv=hospitals[0];
 const now=IsofhApp.session();if(!now||identity!==now.base+'|'+now.account||$('recordId').value.trim()!==id)throw Error('Phiên HIS hoặc ID phiếu đã đổi; lấy lại dữ liệu.');
 source={id,hisBase:session.base,loadedAt:new Date().toISOString(),dto,entity,clsRows,childCatalogRows,benhVien:{ma:bv.ma,ten:bv.ten,maGln:bv.ma_gln},signatures:{}};renderSource();status('status','Đã tạo XML nháp. Xem mã chỉ số, đơn vị đo và nội dung trước khi gửi.');}
function download(name,text,type){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function redact(v){if(Array.isArray(v))return v.map(redact);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,/token|password|private.?key|mat.?khau/i.test(k)?'[ẩn]':redact(x)]));return v;}
async function gatewayCall(path,body,token){const url=gatewayBase($('gatewayUrl').value)+path;const options={method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token,'service-type':'100'}:{})},body:JSON.stringify(body),signal:AbortSignal.timeout(60000),redirect:'error'};let r;try{r=$('transport').value==='local'?await bridge(url,options):await fetch(url,options);}catch(e){throw Error('Không kết nối được cổng. Nếu bị CORS, mở tool qua helper localhost. '+e.message);}const text=await r.text();let json;try{json=JSON.parse(text);}catch{json={raw:text};}return {http:r.status,ok:r.ok,json};}
async function prepare(){const {gln}=checkXml();const url=gatewayBase($('gatewayUrl').value);if($('sender').value.trim()!==gln)throw Error('GLN người gửi phải khớp MACSKCB trong XML.');if(blank($('privateKey').value))throw Error('Nhập private key RSA để ký bản tin.');status('gatewayStatus','Đang ký bản tin tại trình duyệt…');const captured=snapshot();const packet=await envelope($('xml').value,{sender:$('sender').value.trim(),receiver:$('receiver').value.trim(),version:$('version').value.trim()},$('privateKey').value);if(captured!==snapshot())throw Error('XML/cấu hình đã đổi khi ký; tạo lại bản tin.');prepared=packet;preparedSnapshot=captured;$('payload').textContent=JSON.stringify(packet,null,2);$('target').textContent=`POST ${url}/api/platform/data-sync/push\nĐẩy đúng XML đang xem · sender_id ${packet.header.sender_id} · msg_id ${packet.header.msg_id}`;status('gatewayStatus','Bản tin đã sẵn sàng để xem. Chưa gọi cổng.');}
async function push(){if(!prepared||snapshot()!==preparedSnapshot)throw Error('XML/cấu hình đã đổi; tạo lại bản tin trước khi gửi.');checkXml();const packet=prepared,captured=preparedSnapshot;let token=$('gatewayToken').value.trim().replace(/^Bearer\s+/i,'');if(!token){if(!$('gatewayUser').value.trim()||!$('gatewayPassword').value)throw Error('Nhập tài khoản/mật khẩu cổng hoặc token.');status('gatewayStatus','Đang đăng nhập cổng…');const auth=await gatewayCall('/api/auth/login',{username:$('gatewayUser').value.trim(),password:$('gatewayPassword').value});token=gatewayLoginToken(auth);
 const version=auth.json.header?.version;if(version&&version!==packet.header.version){$('version').value=version;invalidate();throw Error('Cổng trả version '+version+'. Đã điền lại; tạo lại bản tin theo version này rồi gửi.');}}
 if(captured!==snapshot()||packet!==prepared)throw Error('Bản tin/cấu hình đã đổi khi đăng nhập; chưa gửi.');status('gatewayStatus','Đang gửi đến '+gatewayBase($('gatewayUrl').value)+'…');invalidate();const result=await gatewayCall('/api/platform/data-sync/push',packet,token);$('response').textContent=JSON.stringify(redact(result),null,2);const h=result.json.header??result.json;const success=result.ok&&['CM_SUCCESS','PS_SYNC_SUCCESS'].includes(h.res_code);status('gatewayStatus',`HTTP ${result.http} · ${h.res_code||'Không có res_code'} · ${h.res_msg||''}\nGiao dịch cổng: ${h.txn_id||'Không có'}\n${success?'Cổng báo gửi thành công.':'Chưa xác nhận gửi thành công.'}`,!success);}
$('load').onclick=()=>safe(load);$('prepare').onclick=()=>safe(prepare,'gatewayStatus');$('push').onclick=()=>safe(push,'gatewayStatus');$('validate').onclick=()=>safe(checkXml,'validation');
for(const id of ['xml','gatewayUrl','sender','receiver','version','privateKey','transport','recordId','gatewayUser','gatewayPassword','gatewayToken'])$(id).addEventListener('input',invalidate);
$('clsSource').onchange=()=>safe(()=>{if(source)renderSource();});
$('downloadXml').onclick=()=>safe(()=>{parseXml($('xml').value);download(`ksk-${source?.id||'draft'}.xml`,$('xml').value,'application/xml;charset=utf-8');});
$('copyXml').onclick=()=>safe(async()=>{await navigator.clipboard.writeText($('xml').value);status('validation','Đã copy XML.');});
$('downloadSource').onclick=()=>safe(()=>{if(!source)throw Error('Chưa có nguồn dữ liệu.');download(`ksk-${source.id}-source.json`,$('sourceData').textContent,'application/json');});
$('sourceFile').onchange=e=>safe(async()=>{const f=e.target.files[0];if(!f)return;if(f.size>10e6)throw Error('File quá lớn.');const s=JSON.parse(await f.text());if(!s.dto||!s.entity||!s.benhVien||!Array.isArray(s.clsRows))throw Error('Cần JSON nguồn gồm dto, entity, benhVien, clsRows.');validId(s.id);source=s;$('recordId').value=s.id;renderSource();});
$('xmlFile').onchange=e=>safe(async()=>{const f=e.target.files[0];if(!f)return;if(f.size>10e6)throw Error('File quá lớn.');const text=await f.text(),doc=parseXml(text);importedSigned=hasSigned(doc)?text:null;$('xml').value=text;invalidate();const gln=doc.getElementsByTagName('THONGTINDONVI')[0]?.getElementsByTagName('MACSKCB')[0]?.textContent.trim();if(gln)$('sender').value=gln;checkXml();});
$('keyFile').onchange=e=>safe(async()=>{const f=e.target.files[0];if(f){if(f.size>100000)throw Error('File key quá lớn.');$('privateKey').value=await f.text();invalidate();}},'gatewayStatus');
$('unsigned').onclick=()=>safe(()=>{const doc=parseXml($('xml').value);[...doc.getElementsByTagNameNS('http://www.w3.org/2000/09/xmldsig#','Signature')].forEach(n=>n.remove());for(const tag of ['CKS_NGUOI_KET_LUAN','CKS_BENH_VIEN'])[...doc.getElementsByTagName(tag)].forEach(n=>n.replaceChildren());$('xml').value=new XMLSerializer().serializeToString(doc);importedSigned=null;invalidate();checkXml();});
function clearSecrets(){$('gatewayPassword').value='';$('gatewayToken').value='';$('privateKey').value='';$('keyFile').value='';invalidate();status('gatewayStatus','Đã xóa mật khẩu, token và private key trong tool.');}
$('clearSecrets').onclick=clearSecrets;
window.addEventListener('isofh-session-change',()=>{source=null;importedSigned=null;invalidate();for(const id of ['xml','summary','sourceData','sql'])$(id).value!==undefined?$(id).value='':$(id).textContent='';$('clsTable').replaceChildren();status('status','Phiên HIS đã đổi; query lại trên server mới.');});
if(['127.0.0.1','localhost'].includes(location.hostname))$('transport').value='local';
