(function(){
 'use strict';
 const $=id=>document.getElementById(id);let workbook=null,sheets=[],sheet=0,page=0,epoch=0,busy=false,controller=null,filename='Query.xlsx';const pageSize=100;
 function status(message,error=false){$('status').textContent=message;$('status').dataset.error=String(error);}
 function attempt(fn){return async()=>{try{await fn();}catch(e){status(e.name==='AbortError'?'Đã dừng chờ response. Query trên server có thể vẫn tiếp tục chạy.':e.message,true);}};}
 function download(data,name,type){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
 function editorInfo(){const text=$('sql').value,before=text.slice(0,$('sql').selectionStart);$('lines').textContent=Array.from({length:text.split('\n').length},(_,i)=>i+1).join('\n');$('editorInfo').textContent=`Dòng ${before.split('\n').length} · Cột ${before.split('\n').at(-1).length+1} · ${text.length.toLocaleString()} ký tự`;$('lines').scrollTop=$('sql').scrollTop;}
 function value(v){return v===null?'NULL':typeof v==='object'?JSON.stringify(v):String(v??'');}
 let jsonView=false;
 function filteredRows(){const rows=sheets[sheet]?.rows||[],term=$('filter').value.toLowerCase();return term?rows.filter(r=>Object.values(r).some(v=>value(v).toLowerCase().includes(term))):rows;}
 function jsonRows(){const rows=filteredRows();return $('jsonScope').value==='filtered'?rows:rows.slice(page*pageSize,(page+1)*pageSize);}
 async function copyText(text){if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(text);return;}const field=document.createElement('textarea');field.value=text;field.style.cssText='position:fixed;left:-9999px;top:0';document.body.append(field);field.select();let copied=false;try{copied=document.execCommand('copy');}finally{field.remove();}if(!copied)throw Error('Trình duyệt chặn clipboard. Dùng Tải JSON hoặc chọn nội dung JSON để copy thủ công.');}
 function highlightJson(text){const node=$('jsonPreview');node.replaceChildren();const pattern=/"(?:\\.|[^"\\])*"\s*:|"(?:\\.|[^"\\])*"|\b(?:true|false|null)\b|-?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?/g;let end=0;for(const match of text.matchAll(pattern)){node.append(document.createTextNode(text.slice(end,match.index)));const span=document.createElement('span'),token=match[0];span.className=token.startsWith('"')?(token.trimEnd().endsWith(':')?'json-key':'json-string'):token==='null'?'json-null':/^(true|false)$/.test(token)?'json-boolean':'json-number';span.textContent=token;node.append(span);end=match.index+token.length;}node.append(document.createTextNode(text.slice(end)));}
 function render(){
  const rows=sheets[sheet]?.rows||[],filtered=filteredRows();page=Math.min(page,Math.max(0,Math.ceil(filtered.length/pageSize)-1));const cols=Object.keys(rows[0]||{}),table=$('table');table.replaceChildren();
  const head=document.createElement('thead'),hr=document.createElement('tr'),copyHead=document.createElement('th');copyHead.textContent='JSON';copyHead.className='row-copy-cell';hr.append(copyHead);for(const col of cols){const th=document.createElement('th');th.textContent=col;hr.append(th);}head.append(hr);table.append(head);
  const body=document.createElement('tbody');for(const row of filtered.slice(page*pageSize,(page+1)*pageSize)){const tr=document.createElement('tr'),action=document.createElement('td'),button=document.createElement('button');action.className='row-copy-cell';button.className='row-copy';button.textContent='Copy';button.title='Copy dòng này dạng JSON';button.onclick=attempt(async()=>{await copyText(JSON.stringify(row,null,2));status('Đã copy JSON của một dòng.');});action.append(button);tr.append(action);for(const col of cols){const td=document.createElement('td');td.textContent=value(row[col]);tr.append(td);}body.append(tr);}table.append(body);
  $('pageInfo').textContent=`${filtered.length.toLocaleString()} / ${rows.length.toLocaleString()} dòng · Trang ${page+1}/${Math.max(1,Math.ceil(filtered.length/pageSize))}`;$('prev').disabled=page===0;$('next').disabled=(page+1)*pageSize>=filtered.length;$('csv').disabled=!rows.length;$('copyJson').disabled=$('saveJson').disabled=!filtered.length;
  $('emptyState').hidden=filtered.length>0;$('emptyState').querySelector('h3').textContent=rows.length?'Không có dòng khớp bộ lọc':'Dữ liệu sẽ hiển thị ở đây';$('tablePane').hidden=jsonView||!filtered.length;$('jsonPane').hidden=!jsonView||!filtered.length;$('viewTable').setAttribute('aria-pressed',String(!jsonView));$('viewJson').setAttribute('aria-pressed',String(jsonView));
  if(jsonView&&filtered.length){const selected=jsonRows(),shown=selected.slice(0,pageSize),text=JSON.stringify(shown,null,2),limit=150000;const clipped=text.length>limit;highlightJson(clipped?text.slice(0,limit)+'\n… (preview rút gọn; dùng Copy JSON / Tải JSON để lấy đầy đủ)':text);$('jsonInfo').textContent=`${sheets[sheet]?.name||'Sheet'} · ${selected.length.toLocaleString()} dòng trong phạm vi JSON · Preview tối đa ${pageSize} dòng / 150.000 ký tự. Copy/Tải lấy đầy đủ phạm vi đã chọn. Chuỗi JSON trong ô Excel được giữ nguyên.`;}
  for(const b of $('sheets').children)b.setAttribute('aria-selected',String(Number(b.dataset.index)===sheet));
 }
 function reset(){workbook=null;sheets=[];sheet=page=0;$('download').disabled=true;$('csv').disabled=true;$('sheets').replaceChildren();$('filter').value='';render();$('provenance').textContent='Chưa có kết quả. Dữ liệu chỉ giữ trong bộ nhớ tab; tải lại trang sẽ xóa.';}
 function setBusy(v){busy=v;$('run').disabled=v;$('cancel').disabled=!v;$('excelFile').disabled=v;}
 async function preview(buffer,name,source,version){
  if(buffer.byteLength>50*1024*1024)throw Error('File vượt 50 MB; hãy thu hẹp query hoặc mở Excel bên ngoài.');
  const bytes=new Uint8Array(buffer);if(bytes[0]!==80||bytes[1]!==75){let msg;try{const payload=JSON.parse(new TextDecoder().decode(buffer));msg=payload.message||'API không trả file Excel.';}catch{msg='Response không phải file XLSX.';}throw Error(msg);}
  // Preserve original export even if the preview parser cannot read it.
  if(version!==epoch)return;workbook=buffer;filename=name;$('download').disabled=false;$('provenance').textContent=source;
  const parsed=await IsofhXlsx.readWorkbook(buffer);if(version!==epoch)return;sheets=parsed;sheet=page=0;$('sheets').replaceChildren();parsed.forEach((s,i)=>{const b=document.createElement('button');b.textContent=`${s.name} (${s.rows.length.toLocaleString()})`;b.dataset.index=i;b.setAttribute('role','tab');b.onclick=()=>{sheet=i;page=0;render();};$('sheets').append(b);});render();status(`Đã đọc ${parsed.length} sheet. Có thể tải Excel gốc. Kiểm tra các sheet lỗi nếu API xuất kèm lỗi SQL.`);
 }
 $('run').onclick=attempt(async()=>{
  if(busy)return;const sql=SqlReadOnly.validate($('sql').value),session=IsofhApp.requireSession();
  if(!IsofhApp.isSafeBase(session.base)&&!confirm(`Bạn đang trên server thật:\n${session.base}\nTài khoản: ${session.account}\nChạy query đọc dữ liệu này?`))return;
  reset();const version=++epoch;controller=new AbortController();setBusy(true);const timer=setTimeout(()=>controller?.abort(),60000);const started=new Date();status(`Đang query trên ${session.base} · ${session.account}…`);
  try{const response=await IsofhApp.request('/dm-mau-du-lieu/db/query',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify([sql]),signal:controller.signal});const buffer=await response.arrayBuffer();if(version!==epoch)return;if(!response.ok)throw Error(`Query thất bại: HTTP ${response.status}.`);await preview(buffer,`Query-${started.toISOString().replace(/[:.]/g,'-')}.xlsx`,`${session.base} · ${session.account} · ${started.toLocaleString('vi-VN')} · Kết quả của SQL tại lúc bấm Chạy (không phải bản sửa sau đó).`,version);}catch(e){if(version===epoch)throw e;}finally{clearTimeout(timer);controller=null;setBusy(false);}
 });
 $('cancel').onclick=()=>{epoch++;controller?.abort();reset();status('Đã dừng chờ. Query trên server có thể vẫn chạy.');};
 $('check').onclick=attempt(()=>{SqlReadOnly.validate($('sql').value);status('Qua kiểm tra chỉ đọc phía trình duyệt. Cú pháp/schema được kiểm tra khi server chạy SQL.');});
 $('copy').onclick=attempt(async()=>{await copyText($('sql').value);status('Đã copy SQL.');});
 $('viewTable').onclick=()=>{jsonView=false;render();};$('viewJson').onclick=()=>{jsonView=true;render();};$('jsonScope').onchange=render;
 $('copyJson').onclick=attempt(async()=>{const rows=jsonRows();await copyText(JSON.stringify(rows,null,2));status(`Đã copy ${rows.length.toLocaleString()} dòng JSON · ${sheets[sheet]?.name||'Sheet'}.`);});
 $('saveJson').onclick=()=>download(JSON.stringify(jsonRows(),null,2),'Query-sheet.json','application/json;charset=utf-8');
 $('save').onclick=()=>download($('sql').value,'Query.sql','text/plain;charset=utf-8');
 $('sqlFile').onchange=attempt(async()=>{const file=$('sqlFile').files[0];if(!file)return;try{if(file.size>200000)throw Error('File SQL vượt 200 KB.');$('sql').value=await file.text();editorInfo();status('Đã mở SQL. Chưa chạy trên HIS.');}finally{$('sqlFile').value='';}});
 $('excelFile').onchange=attempt(async()=>{const file=$('excelFile').files[0];if(!file||busy)return;reset();const version=++epoch;setBusy(true);try{if(file.size>50*1024*1024)throw Error('File vượt 50 MB.');await preview(await file.arrayBuffer(),file.name,`File cục bộ: ${file.name} · Không gọi API, không xác minh nguồn server.`,version);}finally{$('excelFile').value='';setBusy(false);}});
 $('download').onclick=()=>{if(workbook)download(workbook,filename,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');};
 $('csv').onclick=()=>{const rows=sheets[sheet]?.rows||[];if(!rows.length)return;const cols=Object.keys(rows[0]);const cell=v=>{let s=value(v);if(/^[\s]*[=+\-@]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};const text=[cols,...rows.map(r=>cols.map(k=>r[k]))].map(r=>r.map(cell).join(',')).join('\r\n');download('\uFEFF'+text,'Query-sheet.csv','text/csv;charset=utf-8');};
 $('filter').oninput=()=>{page=0;render();};$('prev').onclick=()=>{page--;render();};$('next').onclick=()=>{page++;render();};
 $('snippet').onchange=()=>{const examples={select:'SELECT *\nFROM ten_bang\nWHERE id = 123',cte:'WITH du_lieu AS (\n  SELECT *\n  FROM ten_bang\n  WHERE id = 123\n)\nSELECT * FROM du_lieu'};if(examples[$('snippet').value]){if($('sql').value.trim()&&!confirm('Thay SQL đang soạn bằng mẫu?')){$('snippet').value='';return;}$('sql').value=examples[$('snippet').value];editorInfo();}$('snippet').value='';};
 $('sql').addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();if(!busy)$('run').click();}if(e.key==='Tab'){e.preventDefault();const el=e.target;el.setRangeText('  ',el.selectionStart,el.selectionEnd,'end');editorInfo();}});for(const event of ['input','click','keyup','scroll'])$('sql').addEventListener(event,editorInfo);
 const header=$('appHeader');function sizeHeader(){if(header)document.documentElement.style.setProperty('--console-header-height',header.getBoundingClientRect().height+'px');}if(header&&window.ResizeObserver)new ResizeObserver(sizeHeader).observe(header);window.addEventListener('resize',sizeHeader);sizeHeader();
 window.addEventListener('isofh-session-change',()=>{epoch++;controller?.abort();reset();status('Phiên đã thay đổi. Kết quả cũ đã xóa; SQL đang soạn được giữ.');});editorInfo();render();
})();
